### ISSUE TITLE
"http://dataset-catalogue:8080" er hardkoda som uri for catalog

### ISSUE THREAD

**Issue by stigbd** [Informasjonsforvaltning/dataset-catalogue#59]
Vi må lage ein uri som svarer på feks
```
curl -H "Accept: text/turtle" https://dataset-catalog.fellesdatakatalog.digdir.no/catalogs/<id>
```
Dette må vi standardisere på tvers av alle registreringsløysingane våre.

https://github.com/Informasjonsforvaltning/dataset-catalogue/blob/eddf7524d40f77457678276805591dd9887b038a/src/main/java/no/dcat/controller/CatalogController.java#L249

**Comment by stigbd** [comment]
Henger saman med #58 som også inneheld eit døme.

**Comment by NilsOveTen** [comment]
Etter refaktorering er dette løst for nye kataloger, men må kjøre en ETL for gamle

- [ ] Endre uri for katalogene i dataset-catalog
- [ ] Endre uri for katalogene i fdk-dataset-harvester
- [ ] Kjøre /update på fdk-dataset-harvester
