### ISSUE TITLE
Tilgjengeliggjøre https://dataset-catalog.fellesdatakatalog.digdir.no til internett

### ISSUE THREAD

**Issue by stigbd** [Informasjonsforvaltning/dataset-catalogue#60]

**Comment by valosnah** [comment]
https://github.com/Informasjonsforvaltning/helm-chart/commit/db7499f91ce073afabf663f30b5c74fcb47b6524

Lagt inn i ingressen.
Dataset-catalogue trenger noe arbeid for å kunne håndtere requests
