### ISSUE TITLE
Legg til openAPI spesifikasjon.

### ISSUE THREAD

**Issue by stigbd** [Informasjonsforvaltning/dataset-catalogue#62]
Sjå for eksempel korleis dette er løyst i dataservice-catalog (under /specification)

**Comment by lillelars** [comment]
@stigbd hva er dette? Kan denne lukkes nå?

**Comment by NilsOveTen** [comment]
Løst av https://github.com/Informasjonsforvaltning/dataset-catalog/issues/9
