### ISSUE TITLE
Dataset-catalogue må opprette nye dataset data sources i fdk-admin

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/dataset-catalogue#63]
@valosnah commented on [Tue Aug 11 2020](https://github.com/Informasjonsforvaltning/fdk/issues/3154)

Det nye admin-grensesnittet blir ikke oppdatert med nye datasett-kilder slik det gamle ble.
Dette skal skje med det samme bruker publiserer sitt første datasett.

- [x] Endre slik at dataset-catalogue går mot nye admin
- [x] Se til at nye admin (automatisk) håndterer opprettelse av nye dataset-sources

**Comment by valosnah** [comment]
![image](https://user-images.githubusercontent.com/8625716/92449409-52961500-f1ba-11ea-8631-f7adf74bf475.png)

**Comment by lillelars** [comment]
Denne fungerer nå som forventet. Lukker saken. Testet i demo, i chrome.

**Comment by lillelars** [comment]
@matsjs  Luna fant en liten bug her.. :Ser ut som endepunktet ditt blir oppretet uten '/' mellom catalog og orgNr 

![image](https://user-images.githubusercontent.com/39513382/102778121-42cdc580-4392-11eb-91aa-0c5095182884.png)

**Comment by matsjs** [comment]
> @matsjs Luna fant en liten bug her.. :Ser ut som endepunktet ditt blir oppretet uten '/' mellom catalog og orgNr
> 
> ![image](https://user-images.githubusercontent.com/39513382/102778121-42cdc580-4392-11eb-91aa-0c5095182884.png)
fix:
https://github.com/Informasjonsforvaltning/dataset-catalog/pull/53
